# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf4cb98c37eef7c8abe7a2629e4b11ea07ec406345bb0dbe6dddf334784c53ed74a19c2b2a4616c29f4dfd0c935b88d8ed51b10e745edb531f85b663161e032

test:
  secret_key_base: 92baf48c183cebc9dd379524c02e3f0c54122c7e9e9f77e4f37170473a0af7f2f7dfbdab7c136500ba7b5af6ab482dd72aa6d4eb970e3a3df54fdd07d53e19a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
